---

version: '3.4'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build:
      context: ./
    network_mode: ${NETWORK_MODE:-bridge}
    ports:
      - 80:80
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_NAME=${DB_NAME:-forum}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-supersecret}
      - DJANGO_DB_HOST=${DJANGO_DB_HOST}
      - DJANGO_DB_NAME=${DJANGO_DB_NAME:-brouwers}
      - DJANGO_DB_USER=${DJANGO_DB_USER:-brouwers}
      - DJANGO_DB_PASSWORD=${DJANGO_DB_PASSWORD:-brouwers}
    volumes:
      - ./phpBB3:/var/www/html/phpBB3
      - ${DJANGO_PHPBB_ROOT}/includes/auth/auth_django.php:/var/www/html/phpBB3/includes/auth/auth_django.php
      - ${DJANGO_PHPBB_ROOT}/includes/auth/getdjangouser.php:/var/www/html/phpBB3/includes/auth/getdjangouser.php
      - ${DJANGO_PHPBB_ROOT}/styles/subsilver2_dead_topics:/var/www/html/phpBB3/styles/subsilver2_dead_topics
    depends_on:
      - db

volumes:
  mysql_data:
