---

version: '3.4'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
    volumes:
      - mysql_data:/var/lib/mysql

  memcached:
    image: memcached:1.5-alpine

  web:
    build:
      context: ./
    network_mode: ${NETWORK_MODE:-bridge}
    ports:
      - 80:80
    environment:
      - DEBUG=1
      - DB_HOST=${DB_HOST:-db}
      - DB_NAME=${DB_NAME:-forum}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-supersecret}
      - DJANGO_DB_HOST=${DJANGO_DB_HOST}
      - DJANGO_DB_NAME=${DJANGO_DB_NAME:-brouwers}
      - DJANGO_DB_USER=${DJANGO_DB_USER:-brouwers}
      - DJANGO_DB_PASSWORD=${DJANGO_DB_PASSWORD:-brouwers}
      - MEMCACHED_HOST=memcached
      - PROJECT_DIR=/var/brouwers/src/phpbb
      - NAV_ROOT=/var/brouwers/
      - RAVEN_DSN=${RAVEN_DSN}
    volumes:
      - ./phpBB3:/var/www/html/phpBB3
      - ${INTEGRATION_ROOT}:/var/brouwers
      - ${INTEGRATION_ROOT}static:/var/www/html/static

      - ${INTEGRATION_ROOT}src/phpbb:/var/www/html/phpBB3/src/phpbb
      - ${INTEGRATION_ROOT}src/templates:/var/www/html/phpBB3/src/templates
      - ${INTEGRATION_ROOT}src/conf/settings.php:/var/www/html/phpBB3/src/conf/settings.php

      - ${INTEGRATION_ROOT}src/phpbb/phpBB3/includes/auth/auth_django.php:/var/www/html/phpBB3/includes/auth/auth_django.php
      - ${INTEGRATION_ROOT}src/phpbb/phpBB3/includes/auth/getdjangouser.php:/var/www/html/phpBB3/includes/auth/getdjangouser.php
      - ${INTEGRATION_ROOT}src/phpbb/phpBB3/styles/subsilver2_dead_topics:/var/www/html/phpBB3/styles/subsilver2_dead_topics

    depends_on:
      - db
      - memcached

volumes:
  mysql_data:
